name: Anna-Maria Sichani
description: Modern Greek Literary Studies | Digital Humanities | Electronic publishing & communication 
url: http://amsichani.github.io
permalink: :categories/:title
exclude: [deprecated, vendor, Gemfile, Procfile]

twitter_username:     amsichani
github_username:      asichani
linkedin_username:  Anna-Maria-Sichani

safe: true
highlighter: rouge
markdown: kramdown
gems:
  - jekyll-redirect-from
